name: HyperiorCosmetics_by_Groodian
version: 4.7.3
author: Groodian
main: de.groodian.cosmetics.HyperiorCosmetic

depend: [ HyperiorCore_by_Groodian ]

commands:
  ctest:
    description: Test command